# Generated by Django 5.0.4 on 2024-04-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Question',
        ),
    ]
