# Generated by Django 5.0.4 on 2024-04-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_post_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='upload_time',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
