# Generated by Django 5.0.4 on 2024-04-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_post_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(unique=True, verbose_name='Content'),
        ),
    ]
